### ISSUE TITLE
Mobile Menu doesn't open under iOS

### ISSUE THREAD

**Issue by DasUnicorn** [chaostreff-flensburg/chaostreff-flensburg.de-website#11]
Hi,

the mobile menu isn't working under iOS 16.6.1 on iPhone 12 Pro.

**Comment by DasUnicorn** [comment]
Updating to iOS 17 hasn't solved the issue

**Comment by jonasriecken** [comment]
similar issue for safari on Mac. The menu is closing without a new page opening
